In [1]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()  # 加州房价数据集

housing.data.shape, housing.target.shape

((20640, 8), (20640,))

In [2]:
housing.data[0], housing.target[0]  # 预览第一个样本特征及目标值

(array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
         322.        ,    2.55555556,   37.88      , -122.23      ]),
 4.526)

In [3]:
import numpy as np

housing.data[0].put
# X = np.array([np.append(i, 1) for i in housing.data])
# y =  np.array([[i] for i in housing.target])

X = np.append(housing.data, np.ones((housing.data.shape[0], 1)), axis=1)

# .reshape(-1, 1)：这是一个 NumPy 函数，用于重塑数组。-1 表示根据数组的原始大小自动确定新维度的大小。1 表示新数组的每行包含一个元素，即目标值
# -1 === housing.target.shape[0]
y = housing.target.reshape(-1, 1)


X.shape, y.shape

((20640, 9), (20640, 1))

In [4]:
X[0], y[0]

(array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
         322.        ,    2.55555556,   37.88      , -122.23      ,
           1.        ]),
 array([4.526]))

In [9]:
# import tensorflow as tf

# 实现一,会卡住
# tx = tf.constant(X)
# ty = tf.constant(y)
# tx,ty
# txt = tf.linalg.matrix_transpose(tf.constant(X))
# xtx = tf.matmul(txt,tx)
# # 会卡住？？？
# xtxs = tf.linalg.inv(xtx)
# W = tf.matmul(tf.matmul(xtxs, txt),ty)

In [7]:
import tensorflow as tf


# 实现二
X = tf.constant(X)  # 定义常量
y = tf.constant(y)

XT = tf.transpose(X)  # 根据公式计算拟合系数
XTXS = tf.linalg.inv(tf.matmul(XT, X))
W = tf.matmul(tf.matmul(XTXS, XT), y)

W

<tf.Tensor: shape=(9, 1), dtype=float64, numpy=
array([[ 4.36693293e-01],
       [ 9.43577803e-03],
       [-1.07322041e-01],
       [ 6.45065694e-01],
       [-3.97638942e-06],
       [-3.78654265e-03],
       [-4.21314378e-01],
       [-4.34513755e-01],
       [-3.69419202e+01]])>

In [6]:
# 使用 scikit-learn 提供的线性回归方法建立模型
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(housing.data, housing.target)
model.coef_, model.intercept_

(array([ 4.36693293e-01,  9.43577803e-03, -1.07322041e-01,  6.45065694e-01,
        -3.97638942e-06, -3.78654265e-03, -4.21314378e-01, -4.34513755e-01]),
 -36.94192020718427)