In [1]:
import numpy as np
x = np.array([56, 72, 69, 88, 102, 86, 76, 79, 94, 74])
y = np.array([92, 102, 86, 110, 130, 99, 96, 102, 105, 92])

In [2]:
def least_squares_matrix(x: np.matrix, y: np.matrix):
    """最小二乘法矩阵求解"""
    w = (x.T * x).I * x.T * y
    return w

In [4]:
# 给 x 矩阵补充维度
# np.ones((10, 1)) 创建了一个 10 行 1 列的数组，其中的每个元素都是数字1
# x.reshape 改变数组形状，reshape(10,1),就是将数组转成 10 行 1 列的数组
# np.hstack 将两个数组合并
# 沿着水平轴（即列方向）堆叠两个或多个数组。这意味着它会将输入的数组按列拼接起来，前提是这些数组在垂直轴上（即行数）具有相同的尺寸
x_matrix = np.matrix(np.hstack((np.ones((x.shape[0], 1)), x.reshape(x.shape[0], 1))))
temp = np.hstack((np.ones((x.shape[0], 1)), x.reshape(x.shape[0], 1)))
# y 数组转矩阵
y_matrix = np.matrix(y.reshape(y.shape[0], 1))
temp,x_matrix, y_matrix

(array([[  1.,  56.],
        [  1.,  72.],
        [  1.,  69.],
        [  1.,  88.],
        [  1., 102.],
        [  1.,  86.],
        [  1.,  76.],
        [  1.,  79.],
        [  1.,  94.],
        [  1.,  74.]]),
 matrix([[  1.,  56.],
         [  1.,  72.],
         [  1.,  69.],
         [  1.,  88.],
         [  1., 102.],
         [  1.,  86.],
         [  1.,  76.],
         [  1.,  79.],
         [  1.,  94.],
         [  1.,  74.]]),
 matrix([[ 92],
         [102],
         [ 86],
         [110],
         [130],
         [ 99],
         [ 96],
         [102],
         [105],
         [ 92]]))

In [5]:
least_squares_matrix(x_matrix, y_matrix)


matrix([[41.33509169],
        [ 0.75458428]])